name: 'Validate and Generate module documentation'

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  
  validate:
    name: 'validate terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.1.8'

      - name: 'Terragrunt init'
        run: terraform init

      - name: 'Terragrunt validate'
        run: terraform validate

  docs:
    name: 'generate documentation'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"

      - name: Render terraform docs inside the README.md and push changes back to PR branch for example
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: ./examples/iam_ecr_s3/
          output-file: README.md
          output-method: inject
          git-push: "true"


